# Generated by Django 2.1 on 2018-09-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0002_auto_20180827_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.IntegerField(db_column='Car_ID', primary_key=True, serialize=False)),
                ('car_makename', models.CharField(blank=True, db_column='Car_MakeName', default=None, max_length=50, null=True)),
                ('car_model', models.CharField(blank=True, db_column='Car_Model', default=None, max_length=100, null=True)),
                ('car_series', models.TextField(db_column='Car_Series')),
                ('car_seriesyear', models.CharField(blank=True, db_column='Car_SeriesYear', default=None, max_length=30, null=True)),
                ('car_pricenew', models.CharField(blank=True, db_column='Car_PriceNew', default=None, max_length=20, null=True)),
                ('car_enginesize', models.CharField(blank=True, db_column='Car_EngineSize', default=None, max_length=5, null=True)),
                ('car_fuelsystem', models.CharField(blank=True, db_column='Car_FuelSystem', default=None, max_length=20, null=True)),
                ('car_tankcapacity', models.CharField(blank=True, db_column='Car_TankCapacity', default=None, max_length=5, null=True)),
                ('car_power', models.CharField(blank=True, db_column='Car_Power', default=None, max_length=10, null=True)),
                ('car_seatingcapacity', models.IntegerField(db_column='Car_SeatingCapacity')),
                ('car_standardtransmission', models.CharField(blank=True, db_column='Car_StandardTransmission', default=None, max_length=10, null=True)),
                ('car_bodytype', models.TextField(db_column='Car_BodyType')),
                ('car_drive', models.CharField(blank=True, db_column='Car_Drive', default=None, max_length=5, null=True)),
                ('car_wheelbase', models.CharField(blank=True, db_column='Car_Wheelbase', default=None, max_length=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'cars',
            },
        ),
    ]
